QueryGenerator.hs: fix build failure on ghc-8
ghc-8.0.1 how requires explicit quantification.
Fixes the following build failure:

  [1 of 2] Compiling Database.HSparql.QueryGenerator ( Database/HSparql/QueryGenerator.hs, dist/build/Database/HSparql/QueryGenerator.o )

  Database/HSparql/QueryGenerator.hs:352:31: error:
    Not in scope: type variable ‘a’

Signed-off-by: Sergei Trofimovich <siarheit@google.com>